// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv_layer,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200tsbg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.500000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=41,HLS_SYN_FF=9539,HLS_SYN_LUT=3912}" *)

module conv_layer (
        ap_clk,
        ap_rst_n,
        m_axi_mem_AWVALID,
        m_axi_mem_AWREADY,
        m_axi_mem_AWADDR,
        m_axi_mem_AWID,
        m_axi_mem_AWLEN,
        m_axi_mem_AWSIZE,
        m_axi_mem_AWBURST,
        m_axi_mem_AWLOCK,
        m_axi_mem_AWCACHE,
        m_axi_mem_AWPROT,
        m_axi_mem_AWQOS,
        m_axi_mem_AWREGION,
        m_axi_mem_AWUSER,
        m_axi_mem_WVALID,
        m_axi_mem_WREADY,
        m_axi_mem_WDATA,
        m_axi_mem_WSTRB,
        m_axi_mem_WLAST,
        m_axi_mem_WID,
        m_axi_mem_WUSER,
        m_axi_mem_ARVALID,
        m_axi_mem_ARREADY,
        m_axi_mem_ARADDR,
        m_axi_mem_ARID,
        m_axi_mem_ARLEN,
        m_axi_mem_ARSIZE,
        m_axi_mem_ARBURST,
        m_axi_mem_ARLOCK,
        m_axi_mem_ARCACHE,
        m_axi_mem_ARPROT,
        m_axi_mem_ARQOS,
        m_axi_mem_ARREGION,
        m_axi_mem_ARUSER,
        m_axi_mem_RVALID,
        m_axi_mem_RREADY,
        m_axi_mem_RDATA,
        m_axi_mem_RLAST,
        m_axi_mem_RID,
        m_axi_mem_RUSER,
        m_axi_mem_RRESP,
        m_axi_mem_BVALID,
        m_axi_mem_BREADY,
        m_axi_mem_BRESP,
        m_axi_mem_BID,
        m_axi_mem_BUSER,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 97'd1;
parameter    ap_ST_fsm_state2 = 97'd2;
parameter    ap_ST_fsm_state3 = 97'd4;
parameter    ap_ST_fsm_state4 = 97'd8;
parameter    ap_ST_fsm_state5 = 97'd16;
parameter    ap_ST_fsm_state6 = 97'd32;
parameter    ap_ST_fsm_state7 = 97'd64;
parameter    ap_ST_fsm_state8 = 97'd128;
parameter    ap_ST_fsm_state9 = 97'd256;
parameter    ap_ST_fsm_state10 = 97'd512;
parameter    ap_ST_fsm_state11 = 97'd1024;
parameter    ap_ST_fsm_state12 = 97'd2048;
parameter    ap_ST_fsm_state13 = 97'd4096;
parameter    ap_ST_fsm_state14 = 97'd8192;
parameter    ap_ST_fsm_state15 = 97'd16384;
parameter    ap_ST_fsm_state16 = 97'd32768;
parameter    ap_ST_fsm_state17 = 97'd65536;
parameter    ap_ST_fsm_state18 = 97'd131072;
parameter    ap_ST_fsm_state19 = 97'd262144;
parameter    ap_ST_fsm_state20 = 97'd524288;
parameter    ap_ST_fsm_state21 = 97'd1048576;
parameter    ap_ST_fsm_state22 = 97'd2097152;
parameter    ap_ST_fsm_state23 = 97'd4194304;
parameter    ap_ST_fsm_state24 = 97'd8388608;
parameter    ap_ST_fsm_state25 = 97'd16777216;
parameter    ap_ST_fsm_state26 = 97'd33554432;
parameter    ap_ST_fsm_state27 = 97'd67108864;
parameter    ap_ST_fsm_state28 = 97'd134217728;
parameter    ap_ST_fsm_state29 = 97'd268435456;
parameter    ap_ST_fsm_state30 = 97'd536870912;
parameter    ap_ST_fsm_state31 = 97'd1073741824;
parameter    ap_ST_fsm_state32 = 97'd2147483648;
parameter    ap_ST_fsm_state33 = 97'd4294967296;
parameter    ap_ST_fsm_state34 = 97'd8589934592;
parameter    ap_ST_fsm_state35 = 97'd17179869184;
parameter    ap_ST_fsm_state36 = 97'd34359738368;
parameter    ap_ST_fsm_state37 = 97'd68719476736;
parameter    ap_ST_fsm_state38 = 97'd137438953472;
parameter    ap_ST_fsm_state39 = 97'd274877906944;
parameter    ap_ST_fsm_state40 = 97'd549755813888;
parameter    ap_ST_fsm_state41 = 97'd1099511627776;
parameter    ap_ST_fsm_state42 = 97'd2199023255552;
parameter    ap_ST_fsm_state43 = 97'd4398046511104;
parameter    ap_ST_fsm_state44 = 97'd8796093022208;
parameter    ap_ST_fsm_state45 = 97'd17592186044416;
parameter    ap_ST_fsm_state46 = 97'd35184372088832;
parameter    ap_ST_fsm_state47 = 97'd70368744177664;
parameter    ap_ST_fsm_state48 = 97'd140737488355328;
parameter    ap_ST_fsm_state49 = 97'd281474976710656;
parameter    ap_ST_fsm_state50 = 97'd562949953421312;
parameter    ap_ST_fsm_state51 = 97'd1125899906842624;
parameter    ap_ST_fsm_state52 = 97'd2251799813685248;
parameter    ap_ST_fsm_state53 = 97'd4503599627370496;
parameter    ap_ST_fsm_state54 = 97'd9007199254740992;
parameter    ap_ST_fsm_state55 = 97'd18014398509481984;
parameter    ap_ST_fsm_state56 = 97'd36028797018963968;
parameter    ap_ST_fsm_state57 = 97'd72057594037927936;
parameter    ap_ST_fsm_state58 = 97'd144115188075855872;
parameter    ap_ST_fsm_state59 = 97'd288230376151711744;
parameter    ap_ST_fsm_state60 = 97'd576460752303423488;
parameter    ap_ST_fsm_state61 = 97'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 97'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 97'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 97'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 97'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 97'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 97'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 97'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 97'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 97'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 97'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 97'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 97'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 97'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 97'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 97'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 97'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 97'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 97'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 97'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 97'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 97'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 97'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 97'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 97'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 97'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 97'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 97'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 97'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 97'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 97'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 97'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 97'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 97'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 97'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 97'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 97'd79228162514264337593543950336;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_ID_WIDTH = 1;
parameter    C_M_AXI_MEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_MEM_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_TARGET_ADDR = 0;
parameter    C_M_AXI_MEM_USER_VALUE = 0;
parameter    C_M_AXI_MEM_PROT_VALUE = 0;
parameter    C_M_AXI_MEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_mem_AWVALID;
input   m_axi_mem_AWREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_AWADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_AWID;
output  [7:0] m_axi_mem_AWLEN;
output  [2:0] m_axi_mem_AWSIZE;
output  [1:0] m_axi_mem_AWBURST;
output  [1:0] m_axi_mem_AWLOCK;
output  [3:0] m_axi_mem_AWCACHE;
output  [2:0] m_axi_mem_AWPROT;
output  [3:0] m_axi_mem_AWQOS;
output  [3:0] m_axi_mem_AWREGION;
output  [C_M_AXI_MEM_AWUSER_WIDTH - 1:0] m_axi_mem_AWUSER;
output   m_axi_mem_WVALID;
input   m_axi_mem_WREADY;
output  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_WDATA;
output  [C_M_AXI_MEM_WSTRB_WIDTH - 1:0] m_axi_mem_WSTRB;
output   m_axi_mem_WLAST;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_WID;
output  [C_M_AXI_MEM_WUSER_WIDTH - 1:0] m_axi_mem_WUSER;
output   m_axi_mem_ARVALID;
input   m_axi_mem_ARREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_ARADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_ARID;
output  [7:0] m_axi_mem_ARLEN;
output  [2:0] m_axi_mem_ARSIZE;
output  [1:0] m_axi_mem_ARBURST;
output  [1:0] m_axi_mem_ARLOCK;
output  [3:0] m_axi_mem_ARCACHE;
output  [2:0] m_axi_mem_ARPROT;
output  [3:0] m_axi_mem_ARQOS;
output  [3:0] m_axi_mem_ARREGION;
output  [C_M_AXI_MEM_ARUSER_WIDTH - 1:0] m_axi_mem_ARUSER;
input   m_axi_mem_RVALID;
output   m_axi_mem_RREADY;
input  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_RDATA;
input   m_axi_mem_RLAST;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_RID;
input  [C_M_AXI_MEM_RUSER_WIDTH - 1:0] m_axi_mem_RUSER;
input  [1:0] m_axi_mem_RRESP;
input   m_axi_mem_BVALID;
output   m_axi_mem_BREADY;
input  [1:0] m_axi_mem_BRESP;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_BID;
input  [C_M_AXI_MEM_BUSER_WIDTH - 1:0] m_axi_mem_BUSER;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [96:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] input_offset;
wire   [31:0] output_offset;
wire   [31:0] b;
wire  signed [31:0] od;
wire   [31:0] ox;
wire   [31:0] oy;
wire  signed [31:0] id;
wire   [31:0] ix;
wire   [31:0] iy;
wire   [31:0] s;
wire  signed [31:0] k;
reg    mem_blk_n_AR;
wire    ap_CS_fsm_state32;
wire   [0:0] tmp_6_fu_516_p2;
reg    mem_blk_n_R;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state60;
wire    ap_CS_fsm_state67;
wire    ap_CS_fsm_state61;
wire    ap_CS_fsm_state68;
reg    mem_blk_n_AW;
wire    ap_CS_fsm_state91;
reg    mem_blk_n_W;
wire    ap_CS_fsm_state92;
reg    mem_blk_n_B;
wire    ap_CS_fsm_state97;
reg    mem_AWVALID;
wire    mem_AWREADY;
reg    mem_WVALID;
wire    mem_WREADY;
reg    mem_ARVALID;
wire    mem_ARREADY;
reg   [31:0] mem_ARADDR;
wire    mem_RVALID;
reg    mem_RREADY;
wire   [31:0] mem_RDATA;
wire    mem_RLAST;
wire   [0:0] mem_RID;
wire   [0:0] mem_RUSER;
wire   [1:0] mem_RRESP;
wire    mem_BVALID;
reg    mem_BREADY;
wire   [1:0] mem_BRESP;
wire   [0:0] mem_BID;
wire   [0:0] mem_BUSER;
reg  signed [31:0] k_read_reg_667;
reg   [31:0] s_read_reg_677;
reg  signed [31:0] iy_read_reg_683;
reg  signed [31:0] ix_read_reg_688;
reg  signed [31:0] id_read_reg_693;
reg  signed [31:0] oy_read_reg_701;
reg  signed [31:0] ox_read_reg_707;
reg  signed [31:0] od_read_reg_713;
reg   [31:0] b_read_reg_721;
reg   [29:0] tmp_2_reg_726;
reg   [29:0] tmp_3_reg_731;
wire  signed [31:0] grp_fu_357_p2;
reg  signed [31:0] tmp_reg_736;
wire    ap_CS_fsm_state7;
wire  signed [31:0] grp_fu_363_p2;
reg  signed [31:0] tmp13_reg_741;
wire   [31:0] grp_fu_389_p2;
reg   [31:0] num_weights_reg_746;
wire    ap_CS_fsm_state14;
wire   [31:0] tmp_s_fu_393_p1;
reg   [31:0] tmp_s_reg_752;
wire   [31:0] tmp_5_fu_396_p1;
reg   [31:0] tmp_5_reg_758;
wire   [31:0] tmp16_fu_399_p2;
reg   [31:0] tmp16_reg_763;
wire   [31:0] next_mul8_fu_404_p2;
reg   [31:0] next_mul8_reg_768;
wire    ap_CS_fsm_state15;
wire   [31:0] next_mul6_fu_409_p2;
reg   [31:0] next_mul6_reg_773;
wire   [30:0] b_1_fu_423_p2;
reg   [30:0] b_1_reg_781;
wire   [31:0] next_mul4_fu_429_p2;
reg   [31:0] next_mul4_reg_786;
wire    ap_CS_fsm_state16;
wire   [31:0] o_d_cast_fu_434_p1;
reg   [31:0] o_d_cast_reg_791;
wire   [30:0] o_d_1_fu_443_p2;
reg   [30:0] o_d_1_reg_799;
wire  signed [31:0] tmp1_fu_449_p2;
reg  signed [31:0] tmp1_reg_804;
wire   [0:0] tmp_7_fu_438_p2;
wire   [31:0] tmp14_fu_459_p2;
reg   [31:0] tmp14_reg_809;
wire    ap_CS_fsm_state22;
reg   [31:0] mem_addr_reg_814;
wire    ap_CS_fsm_state23;
wire   [31:0] grp_fu_455_p2;
reg   [31:0] tmp2_reg_820;
wire   [31:0] next_mul2_fu_473_p2;
reg   [31:0] next_mul2_reg_825;
wire    ap_CS_fsm_state24;
wire   [30:0] o_y_1_fu_487_p2;
reg   [30:0] o_y_1_reg_833;
wire  signed [31:0] tmp7_fu_493_p2;
reg  signed [31:0] tmp7_reg_838;
wire   [0:0] tmp_1_fu_482_p2;
wire   [31:0] tmp_8_fu_502_p2;
reg   [31:0] tmp_8_reg_843;
wire    ap_CS_fsm_state31;
wire   [31:0] grp_fu_498_p2;
reg   [31:0] tmp12_reg_848;
wire   [31:0] next_mul_fu_507_p2;
reg   [31:0] next_mul_reg_853;
reg    ap_sig_ioackin_mem_ARREADY;
reg    ap_block_state32_io;
wire   [31:0] o_x_cast_fu_512_p1;
reg   [31:0] o_x_cast_reg_858;
wire   [30:0] o_x_1_fu_521_p2;
reg   [30:0] o_x_1_reg_866;
reg   [31:0] output_element_reg_871;
wire   [31:0] tmp_10_fu_527_p2;
reg   [31:0] tmp_10_reg_876;
wire    ap_CS_fsm_state40;
wire   [30:0] i_d_1_fu_541_p2;
reg   [30:0] i_d_1_reg_884;
wire    ap_CS_fsm_state41;
wire  signed [31:0] tmp4_fu_547_p2;
reg  signed [31:0] tmp4_reg_889;
wire   [0:0] tmp_11_fu_536_p2;
wire  signed [31:0] tmp9_fu_553_p2;
reg  signed [31:0] tmp9_reg_894;
wire   [31:0] tmp15_fu_559_p2;
reg   [31:0] tmp15_reg_899;
wire   [31:0] grp_fu_563_p2;
reg   [31:0] tmp5_reg_904;
wire    ap_CS_fsm_state48;
wire   [31:0] grp_fu_567_p2;
reg   [31:0] tmp10_reg_909;
wire   [31:0] iiy_1_fu_576_p2;
reg   [31:0] iiy_1_reg_917;
wire    ap_CS_fsm_state49;
wire  signed [31:0] tmp3_fu_582_p2;
reg  signed [31:0] tmp3_reg_922;
wire   [0:0] tmp_13_fu_571_p2;
wire  signed [31:0] tmp8_fu_587_p2;
reg  signed [31:0] tmp8_reg_927;
wire   [31:0] grp_fu_592_p2;
reg   [31:0] tmp6_reg_932;
wire    ap_CS_fsm_state56;
wire   [31:0] grp_fu_596_p2;
reg   [31:0] tmp11_reg_937;
wire   [31:0] iix_1_fu_605_p2;
reg   [31:0] iix_1_reg_945;
wire    ap_CS_fsm_state57;
wire   [31:0] tmp17_fu_611_p2;
reg   [31:0] tmp17_reg_950;
wire   [0:0] tmp_14_fu_600_p2;
wire   [31:0] tmp19_fu_616_p2;
reg   [31:0] tmp19_reg_955;
wire   [31:0] i_x_1_fu_621_p2;
reg   [31:0] i_x_1_reg_960;
wire   [31:0] i_y_1_fu_627_p2;
wire   [31:0] tmp18_fu_633_p2;
reg   [31:0] tmp18_reg_970;
wire    ap_CS_fsm_state58;
wire   [31:0] tmp_16_fu_637_p2;
reg   [31:0] tmp_16_reg_975;
wire   [31:0] tmp_15_fu_641_p2;
reg   [31:0] tmp_15_reg_980;
wire    ap_CS_fsm_state59;
reg   [31:0] input_element_reg_997;
reg   [31:0] weight_element_reg_1002;
wire   [31:0] grp_fu_353_p2;
reg   [31:0] tmp_17_reg_1007;
wire    ap_CS_fsm_state76;
wire   [31:0] grp_fu_348_p2;
wire    ap_CS_fsm_state89;
wire   [31:0] tmp_12_fu_657_p2;
reg   [31:0] tmp_12_reg_1017;
wire    ap_CS_fsm_state90;
reg    ap_sig_ioackin_mem_AWREADY;
reg   [30:0] b_s_reg_155;
reg   [31:0] phi_mul5_reg_166;
reg   [31:0] phi_mul7_reg_178;
reg   [30:0] o_d_reg_190;
wire   [0:0] tmp_4_fu_418_p2;
reg   [31:0] phi_mul3_reg_201;
reg   [30:0] o_y_reg_213;
reg   [31:0] i_y_reg_224;
reg   [30:0] o_x_reg_236;
reg   [31:0] i_x_reg_247;
reg   [31:0] output_element1_reg_259;
reg   [30:0] i_d_reg_270;
reg   [31:0] output_element_1_reg_281;
reg   [31:0] i_y1_reg_293;
reg   [31:0] iiy_reg_304;
reg   [31:0] output_element_2_reg_315;
reg   [31:0] i_x1_reg_327;
reg   [31:0] iix_reg_337;
wire   [31:0] tmp_9_fu_463_p2;
reg    ap_reg_ioackin_mem_ARREADY;
reg    ap_reg_ioackin_mem_AWREADY;
reg    ap_reg_ioackin_mem_WREADY;
reg    ap_sig_ioackin_mem_WREADY;
wire    ap_CS_fsm_state77;
wire    ap_CS_fsm_state69;
wire    ap_CS_fsm_state8;
wire   [31:0] b_cast_fu_414_p1;
wire    ap_CS_fsm_state17;
wire   [31:0] o_y_cast_fu_478_p1;
wire    ap_CS_fsm_state25;
wire   [31:0] i_d_cast_fu_532_p1;
wire    ap_CS_fsm_state42;
wire    ap_CS_fsm_state50;
reg   [96:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 97'd1;
#0 ap_reg_ioackin_mem_ARREADY = 1'b0;
#0 ap_reg_ioackin_mem_AWREADY = 1'b0;
#0 ap_reg_ioackin_mem_WREADY = 1'b0;
end

conv_layer_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
conv_layer_CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .input_offset(input_offset),
    .output_offset(output_offset),
    .b(b),
    .od(od),
    .ox(ox),
    .oy(oy),
    .id(id),
    .ix(ix),
    .iy(iy),
    .s(s),
    .k(k)
);

conv_layer_mem_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEM_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_MEM_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_MEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEM_CACHE_VALUE ))
conv_layer_mem_m_axi_U(
    .AWVALID(m_axi_mem_AWVALID),
    .AWREADY(m_axi_mem_AWREADY),
    .AWADDR(m_axi_mem_AWADDR),
    .AWID(m_axi_mem_AWID),
    .AWLEN(m_axi_mem_AWLEN),
    .AWSIZE(m_axi_mem_AWSIZE),
    .AWBURST(m_axi_mem_AWBURST),
    .AWLOCK(m_axi_mem_AWLOCK),
    .AWCACHE(m_axi_mem_AWCACHE),
    .AWPROT(m_axi_mem_AWPROT),
    .AWQOS(m_axi_mem_AWQOS),
    .AWREGION(m_axi_mem_AWREGION),
    .AWUSER(m_axi_mem_AWUSER),
    .WVALID(m_axi_mem_WVALID),
    .WREADY(m_axi_mem_WREADY),
    .WDATA(m_axi_mem_WDATA),
    .WSTRB(m_axi_mem_WSTRB),
    .WLAST(m_axi_mem_WLAST),
    .WID(m_axi_mem_WID),
    .WUSER(m_axi_mem_WUSER),
    .ARVALID(m_axi_mem_ARVALID),
    .ARREADY(m_axi_mem_ARREADY),
    .ARADDR(m_axi_mem_ARADDR),
    .ARID(m_axi_mem_ARID),
    .ARLEN(m_axi_mem_ARLEN),
    .ARSIZE(m_axi_mem_ARSIZE),
    .ARBURST(m_axi_mem_ARBURST),
    .ARLOCK(m_axi_mem_ARLOCK),
    .ARCACHE(m_axi_mem_ARCACHE),
    .ARPROT(m_axi_mem_ARPROT),
    .ARQOS(m_axi_mem_ARQOS),
    .ARREGION(m_axi_mem_ARREGION),
    .ARUSER(m_axi_mem_ARUSER),
    .RVALID(m_axi_mem_RVALID),
    .RREADY(m_axi_mem_RREADY),
    .RDATA(m_axi_mem_RDATA),
    .RLAST(m_axi_mem_RLAST),
    .RID(m_axi_mem_RID),
    .RUSER(m_axi_mem_RUSER),
    .RRESP(m_axi_mem_RRESP),
    .BVALID(m_axi_mem_BVALID),
    .BREADY(m_axi_mem_BREADY),
    .BRESP(m_axi_mem_BRESP),
    .BID(m_axi_mem_BID),
    .BUSER(m_axi_mem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(mem_ARVALID),
    .I_ARREADY(mem_ARREADY),
    .I_ARADDR(mem_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(mem_RVALID),
    .I_RREADY(mem_RREADY),
    .I_RDATA(mem_RDATA),
    .I_RID(mem_RID),
    .I_RUSER(mem_RUSER),
    .I_RRESP(mem_RRESP),
    .I_RLAST(mem_RLAST),
    .I_AWVALID(mem_AWVALID),
    .I_AWREADY(mem_AWREADY),
    .I_AWADDR(tmp_12_reg_1017),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(mem_WVALID),
    .I_WREADY(mem_WREADY),
    .I_WDATA(output_element1_reg_259),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(mem_BVALID),
    .I_BREADY(mem_BREADY),
    .I_BRESP(mem_BRESP),
    .I_BID(mem_BID),
    .I_BUSER(mem_BUSER)
);

conv_layer_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_fadd_3bkb_U0(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(output_element_2_reg_315),
    .din1(tmp_17_reg_1007),
    .ce(1'b1),
    .dout(grp_fu_348_p2)
);

conv_layer_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_fmul_3cud_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(input_element_reg_997),
    .din1(weight_element_reg_1002),
    .ce(1'b1),
    .dout(grp_fu_353_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(od),
    .din1(k),
    .ce(1'b1),
    .dout(grp_fu_357_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(id),
    .din1(k),
    .ce(1'b1),
    .dout(grp_fu_363_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp13_reg_741),
    .din1(tmp_reg_736),
    .ce(1'b1),
    .dout(grp_fu_389_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp1_reg_804),
    .din1(oy_read_reg_701),
    .ce(1'b1),
    .dout(grp_fu_455_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp7_reg_838),
    .din1(ox_read_reg_707),
    .ce(1'b1),
    .dout(grp_fu_498_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp4_reg_889),
    .din1(iy_read_reg_683),
    .ce(1'b1),
    .dout(grp_fu_563_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp9_reg_894),
    .din1(k_read_reg_667),
    .ce(1'b1),
    .dout(grp_fu_567_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp3_reg_922),
    .din1(ix_read_reg_688),
    .ce(1'b1),
    .dout(grp_fu_592_p2)
);

conv_layer_mul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_layer_mul_32dEe_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp8_reg_927),
    .din1(k_read_reg_667),
    .ce(1'b1),
    .dout(grp_fu_596_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_mem_ARREADY <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state60) & (ap_sig_ioackin_mem_ARREADY == 1'b1)) | ((1'b1 == ap_CS_fsm_state61) & (ap_sig_ioackin_mem_ARREADY == 1'b1)) | ((1'b1 == ap_CS_fsm_state32) & (tmp_6_fu_516_p2 == 1'd1) & (ap_block_state32_io == 1'b0)))) begin
            ap_reg_ioackin_mem_ARREADY <= 1'b0;
        end else if ((((1'b1 == ap_CS_fsm_state32) & (tmp_6_fu_516_p2 == 1'd1) & (1'b1 == mem_ARREADY)) | ((1'b1 == ap_CS_fsm_state60) & (1'b1 == mem_ARREADY)) | ((1'b1 == ap_CS_fsm_state61) & (1'b1 == mem_ARREADY)))) begin
            ap_reg_ioackin_mem_ARREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_mem_AWREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state91)) begin
            if ((ap_sig_ioackin_mem_AWREADY == 1'b1)) begin
                ap_reg_ioackin_mem_AWREADY <= 1'b0;
            end else if ((1'b1 == mem_AWREADY)) begin
                ap_reg_ioackin_mem_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_mem_WREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state92)) begin
            if ((ap_sig_ioackin_mem_WREADY == 1'b1)) begin
                ap_reg_ioackin_mem_WREADY <= 1'b0;
            end else if ((1'b1 == mem_WREADY)) begin
                ap_reg_ioackin_mem_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (tmp_7_fu_438_p2 == 1'd0))) begin
        b_s_reg_155 <= b_1_reg_781;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        b_s_reg_155 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state49) & (1'd0 == tmp_13_fu_571_p2))) begin
        i_d_reg_270 <= i_d_1_reg_884;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        i_d_reg_270 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state89)) begin
        i_x1_reg_327 <= i_x_1_reg_960;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        i_x1_reg_327 <= i_x_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        i_x_reg_247 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state97) & (mem_BVALID == 1'b1))) begin
        i_x_reg_247 <= next_mul_reg_853;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state57) & (1'd0 == tmp_14_fu_600_p2))) begin
        i_y1_reg_293 <= i_y_1_fu_627_p2;
    end else if ((1'b1 == ap_CS_fsm_state48)) begin
        i_y1_reg_293 <= i_y_reg_224;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state32) & (ap_block_state32_io == 1'b0) & (tmp_6_fu_516_p2 == 1'd0))) begin
        i_y_reg_224 <= next_mul2_reg_825;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        i_y_reg_224 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state89)) begin
        iix_reg_337 <= iix_1_reg_945;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        iix_reg_337 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state57) & (1'd0 == tmp_14_fu_600_p2))) begin
        iiy_reg_304 <= iiy_1_reg_917;
    end else if ((1'b1 == ap_CS_fsm_state48)) begin
        iiy_reg_304 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (1'd1 == tmp_4_fu_418_p2))) begin
        o_d_reg_190 <= 31'd0;
    end else if (((1'b1 == ap_CS_fsm_state24) & (tmp_1_fu_482_p2 == 1'd0))) begin
        o_d_reg_190 <= o_d_1_reg_799;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        o_x_reg_236 <= 31'd0;
    end else if (((1'b1 == ap_CS_fsm_state97) & (mem_BVALID == 1'b1))) begin
        o_x_reg_236 <= o_x_1_reg_866;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state32) & (ap_block_state32_io == 1'b0) & (tmp_6_fu_516_p2 == 1'd0))) begin
        o_y_reg_213 <= o_y_1_reg_833;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        o_y_reg_213 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state49) & (1'd0 == tmp_13_fu_571_p2))) begin
        output_element1_reg_259 <= output_element_1_reg_281;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        output_element1_reg_259 <= output_element_reg_871;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state57) & (1'd0 == tmp_14_fu_600_p2))) begin
        output_element_1_reg_281 <= output_element_2_reg_315;
    end else if ((1'b1 == ap_CS_fsm_state48)) begin
        output_element_1_reg_281 <= output_element1_reg_259;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state89)) begin
        output_element_2_reg_315 <= grp_fu_348_p2;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        output_element_2_reg_315 <= output_element_1_reg_281;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (1'd1 == tmp_4_fu_418_p2))) begin
        phi_mul3_reg_201 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state24) & (tmp_1_fu_482_p2 == 1'd0))) begin
        phi_mul3_reg_201 <= next_mul4_reg_786;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (tmp_7_fu_438_p2 == 1'd0))) begin
        phi_mul5_reg_166 <= next_mul6_reg_773;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        phi_mul5_reg_166 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (tmp_7_fu_438_p2 == 1'd0))) begin
        phi_mul7_reg_178 <= next_mul8_reg_768;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        phi_mul7_reg_178 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        b_1_reg_781 <= b_1_fu_423_p2;
        next_mul6_reg_773 <= next_mul6_fu_409_p2;
        next_mul8_reg_768 <= next_mul8_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        b_read_reg_721 <= b;
        id_read_reg_693 <= id;
        ix_read_reg_688 <= ix;
        iy_read_reg_683 <= iy;
        k_read_reg_667 <= k;
        od_read_reg_713 <= od;
        ox_read_reg_707 <= ox;
        oy_read_reg_701 <= oy;
        s_read_reg_677 <= s;
        tmp_2_reg_726 <= {{input_offset[31:2]}};
        tmp_3_reg_731 <= {{output_offset[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        i_d_1_reg_884 <= i_d_1_fu_541_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state57) & (1'd1 == tmp_14_fu_600_p2))) begin
        i_x_1_reg_960 <= i_x_1_fu_621_p2;
        tmp17_reg_950 <= tmp17_fu_611_p2;
        tmp19_reg_955 <= tmp19_fu_616_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        iix_1_reg_945 <= iix_1_fu_605_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        iiy_1_reg_917 <= iiy_1_fu_576_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state67) & (mem_RVALID == 1'b1))) begin
        input_element_reg_997 <= mem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        mem_addr_reg_814 <= tmp_9_fu_463_p2;
        tmp2_reg_820 <= grp_fu_455_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        next_mul2_reg_825 <= next_mul2_fu_473_p2;
        o_y_1_reg_833 <= o_y_1_fu_487_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        next_mul4_reg_786 <= next_mul4_fu_429_p2;
        o_d_1_reg_799 <= o_d_1_fu_443_p2;
        o_d_cast_reg_791[30 : 0] <= o_d_cast_fu_434_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state32) & (ap_block_state32_io == 1'b0))) begin
        next_mul_reg_853 <= next_mul_fu_507_p2;
        o_x_1_reg_866 <= o_x_1_fu_521_p2;
        o_x_cast_reg_858[30 : 0] <= o_x_cast_fu_512_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        num_weights_reg_746 <= grp_fu_389_p2;
        tmp16_reg_763 <= tmp16_fu_399_p2;
        tmp_5_reg_758[29 : 0] <= tmp_5_fu_396_p1[29 : 0];
        tmp_s_reg_752[29 : 0] <= tmp_s_fu_393_p1[29 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state39) & (mem_RVALID == 1'b1))) begin
        output_element_reg_871 <= mem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        tmp10_reg_909 <= grp_fu_567_p2;
        tmp5_reg_904 <= grp_fu_563_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        tmp11_reg_937 <= grp_fu_596_p2;
        tmp6_reg_932 <= grp_fu_592_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        tmp12_reg_848 <= grp_fu_498_p2;
        tmp_8_reg_843 <= tmp_8_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp13_reg_741 <= grp_fu_363_p2;
        tmp_reg_736 <= grp_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        tmp14_reg_809 <= tmp14_fu_459_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state41) & (tmp_11_fu_536_p2 == 1'd0))) begin
        tmp15_reg_899 <= tmp15_fu_559_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        tmp18_reg_970 <= tmp18_fu_633_p2;
        tmp_16_reg_975 <= tmp_16_fu_637_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (1'd1 == tmp_7_fu_438_p2))) begin
        tmp1_reg_804 <= tmp1_fu_449_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state49) & (1'd1 == tmp_13_fu_571_p2))) begin
        tmp3_reg_922 <= tmp3_fu_582_p2;
        tmp8_reg_927 <= tmp8_fu_587_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state41) & (1'd1 == tmp_11_fu_536_p2))) begin
        tmp4_reg_889 <= tmp4_fu_547_p2;
        tmp9_reg_894 <= tmp9_fu_553_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'd1 == tmp_1_fu_482_p2))) begin
        tmp7_reg_838 <= tmp7_fu_493_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        tmp_10_reg_876 <= tmp_10_fu_527_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        tmp_12_reg_1017 <= tmp_12_fu_657_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        tmp_15_reg_980 <= tmp_15_fu_641_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        tmp_17_reg_1007 <= grp_fu_353_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state68) & (mem_RVALID == 1'b1))) begin
        weight_element_reg_1002 <= mem_RDATA;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (1'd0 == tmp_4_fu_418_p2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (1'd0 == tmp_4_fu_418_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_mem_ARREADY)) begin
        ap_sig_ioackin_mem_ARREADY = mem_ARREADY;
    end else begin
        ap_sig_ioackin_mem_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_mem_AWREADY)) begin
        ap_sig_ioackin_mem_AWREADY = mem_AWREADY;
    end else begin
        ap_sig_ioackin_mem_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_mem_WREADY)) begin
        ap_sig_ioackin_mem_WREADY = mem_WREADY;
    end else begin
        ap_sig_ioackin_mem_WREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_mem_ARREADY)) begin
        if ((1'b1 == ap_CS_fsm_state61)) begin
            mem_ARADDR = tmp_16_reg_975;
        end else if ((1'b1 == ap_CS_fsm_state60)) begin
            mem_ARADDR = tmp_15_reg_980;
        end else if (((1'b1 == ap_CS_fsm_state32) & (tmp_6_fu_516_p2 == 1'd1))) begin
            mem_ARADDR = mem_addr_reg_814;
        end else begin
            mem_ARADDR = 'bx;
        end
    end else begin
        mem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state32) & (tmp_6_fu_516_p2 == 1'd1) & (1'b0 == ap_reg_ioackin_mem_ARREADY)) | ((1'b1 == ap_CS_fsm_state60) & (1'b0 == ap_reg_ioackin_mem_ARREADY)) | ((1'b1 == ap_CS_fsm_state61) & (1'b0 == ap_reg_ioackin_mem_ARREADY)))) begin
        mem_ARVALID = 1'b1;
    end else begin
        mem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state91) & (1'b0 == ap_reg_ioackin_mem_AWREADY))) begin
        mem_AWVALID = 1'b1;
    end else begin
        mem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state97) & (mem_BVALID == 1'b1))) begin
        mem_BREADY = 1'b1;
    end else begin
        mem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state39) & (mem_RVALID == 1'b1)) | ((1'b1 == ap_CS_fsm_state67) & (mem_RVALID == 1'b1)) | ((1'b1 == ap_CS_fsm_state68) & (mem_RVALID == 1'b1)))) begin
        mem_RREADY = 1'b1;
    end else begin
        mem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state92) & (1'b0 == ap_reg_ioackin_mem_WREADY))) begin
        mem_WVALID = 1'b1;
    end else begin
        mem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state32) & (tmp_6_fu_516_p2 == 1'd1)) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state61))) begin
        mem_blk_n_AR = m_axi_mem_ARREADY;
    end else begin
        mem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state91)) begin
        mem_blk_n_AW = m_axi_mem_AWREADY;
    end else begin
        mem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state97)) begin
        mem_blk_n_B = m_axi_mem_BVALID;
    end else begin
        mem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state68))) begin
        mem_blk_n_R = m_axi_mem_RVALID;
    end else begin
        mem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state92)) begin
        mem_blk_n_W = m_axi_mem_WREADY;
    end else begin
        mem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (1'd0 == tmp_4_fu_418_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (tmp_7_fu_438_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((1'b1 == ap_CS_fsm_state24) & (tmp_1_fu_482_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((1'b1 == ap_CS_fsm_state32) & (ap_block_state32_io == 1'b0) & (tmp_6_fu_516_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else if (((1'b1 == ap_CS_fsm_state32) & (tmp_6_fu_516_p2 == 1'd1) & (ap_block_state32_io == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            if (((1'b1 == ap_CS_fsm_state39) & (mem_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            if (((1'b1 == ap_CS_fsm_state41) & (tmp_11_fu_536_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state90;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            if (((1'b1 == ap_CS_fsm_state49) & (1'd0 == tmp_13_fu_571_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            if (((1'b1 == ap_CS_fsm_state57) & (1'd0 == tmp_14_fu_600_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            if (((1'b1 == ap_CS_fsm_state60) & (ap_sig_ioackin_mem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state61;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end
        end
        ap_ST_fsm_state61 : begin
            if (((1'b1 == ap_CS_fsm_state61) & (ap_sig_ioackin_mem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state62;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state61;
            end
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            if (((1'b1 == ap_CS_fsm_state67) & (mem_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state68;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state67;
            end
        end
        ap_ST_fsm_state68 : begin
            if (((1'b1 == ap_CS_fsm_state68) & (mem_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state68;
            end
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            if (((1'b1 == ap_CS_fsm_state91) & (ap_sig_ioackin_mem_AWREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state92;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state91;
            end
        end
        ap_ST_fsm_state92 : begin
            if (((1'b1 == ap_CS_fsm_state92) & (ap_sig_ioackin_mem_WREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state93;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state92;
            end
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            if (((1'b1 == ap_CS_fsm_state97) & (mem_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state97;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd66];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state89 = ap_CS_fsm[32'd88];

assign ap_CS_fsm_state90 = ap_CS_fsm[32'd89];

assign ap_CS_fsm_state91 = ap_CS_fsm[32'd90];

assign ap_CS_fsm_state92 = ap_CS_fsm[32'd91];

assign ap_CS_fsm_state97 = ap_CS_fsm[32'd96];

always @ (*) begin
    ap_block_state32_io = ((tmp_6_fu_516_p2 == 1'd1) & (1'b0 == ap_sig_ioackin_mem_ARREADY));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign b_1_fu_423_p2 = (b_s_reg_155 + 31'd1);

assign b_cast_fu_414_p1 = b_s_reg_155;

assign i_d_1_fu_541_p2 = (i_d_reg_270 + 31'd1);

assign i_d_cast_fu_532_p1 = i_d_reg_270;

assign i_x_1_fu_621_p2 = (i_x1_reg_327 + 32'd1);

assign i_y_1_fu_627_p2 = (i_y1_reg_293 + 32'd1);

assign iix_1_fu_605_p2 = (iix_reg_337 + 32'd1);

assign iiy_1_fu_576_p2 = (iiy_reg_304 + 32'd1);

assign next_mul2_fu_473_p2 = (i_y_reg_224 + s_read_reg_677);

assign next_mul4_fu_429_p2 = ($signed(phi_mul3_reg_201) + $signed(id_read_reg_693));

assign next_mul6_fu_409_p2 = ($signed(phi_mul5_reg_166) + $signed(id_read_reg_693));

assign next_mul8_fu_404_p2 = ($signed(phi_mul7_reg_178) + $signed(od_read_reg_713));

assign next_mul_fu_507_p2 = (i_x_reg_247 + s_read_reg_677);

assign o_d_1_fu_443_p2 = (o_d_reg_190 + 31'd1);

assign o_d_cast_fu_434_p1 = o_d_reg_190;

assign o_x_1_fu_521_p2 = (o_x_reg_236 + 31'd1);

assign o_x_cast_fu_512_p1 = o_x_reg_236;

assign o_y_1_fu_487_p2 = (o_y_reg_213 + 31'd1);

assign o_y_cast_fu_478_p1 = o_y_reg_213;

assign tmp14_fu_459_p2 = (tmp_s_reg_752 + o_d_cast_reg_791);

assign tmp15_fu_559_p2 = (tmp_5_reg_758 + o_x_cast_reg_858);

assign tmp16_fu_399_p2 = ($signed(tmp_s_fu_393_p1) + $signed(od_read_reg_713));

assign tmp17_fu_611_p2 = (tmp6_reg_932 + i_x1_reg_327);

assign tmp18_fu_633_p2 = (tmp17_reg_950 + num_weights_reg_746);

assign tmp19_fu_616_p2 = (tmp_s_reg_752 + iix_reg_337);

assign tmp1_fu_449_p2 = (o_d_cast_fu_434_p1 + phi_mul7_reg_178);

assign tmp3_fu_582_p2 = (i_y1_reg_293 + tmp5_reg_904);

assign tmp4_fu_547_p2 = (i_d_cast_fu_532_p1 + phi_mul5_reg_166);

assign tmp7_fu_493_p2 = (o_y_cast_fu_478_p1 + tmp2_reg_820);

assign tmp8_fu_587_p2 = (iiy_reg_304 + tmp10_reg_909);

assign tmp9_fu_553_p2 = (i_d_cast_fu_532_p1 + phi_mul3_reg_201);

assign tmp_10_fu_527_p2 = ($signed(i_x_reg_247) + $signed(k_read_reg_667));

assign tmp_11_fu_536_p2 = (($signed(i_d_cast_fu_532_p1) < $signed(id_read_reg_693)) ? 1'b1 : 1'b0);

assign tmp_12_fu_657_p2 = (tmp15_reg_899 + tmp12_reg_848);

assign tmp_13_fu_571_p2 = (($signed(i_y1_reg_293) < $signed(tmp_8_reg_843)) ? 1'b1 : 1'b0);

assign tmp_14_fu_600_p2 = (($signed(i_x1_reg_327) < $signed(tmp_10_reg_876)) ? 1'b1 : 1'b0);

assign tmp_15_fu_641_p2 = (tmp18_reg_970 + tmp16_reg_763);

assign tmp_16_fu_637_p2 = (tmp19_reg_955 + tmp11_reg_937);

assign tmp_1_fu_482_p2 = (($signed(o_y_cast_fu_478_p1) < $signed(oy_read_reg_701)) ? 1'b1 : 1'b0);

assign tmp_4_fu_418_p2 = (($signed(b_cast_fu_414_p1) < $signed(b_read_reg_721)) ? 1'b1 : 1'b0);

assign tmp_5_fu_396_p1 = tmp_3_reg_731;

assign tmp_6_fu_516_p2 = (($signed(o_x_cast_fu_512_p1) < $signed(ox_read_reg_707)) ? 1'b1 : 1'b0);

assign tmp_7_fu_438_p2 = (($signed(o_d_cast_fu_434_p1) < $signed(od_read_reg_713)) ? 1'b1 : 1'b0);

assign tmp_8_fu_502_p2 = ($signed(i_y_reg_224) + $signed(k_read_reg_667));

assign tmp_9_fu_463_p2 = (tmp14_reg_809 + num_weights_reg_746);

assign tmp_s_fu_393_p1 = tmp_2_reg_726;

always @ (posedge ap_clk) begin
    tmp_s_reg_752[31:30] <= 2'b00;
    tmp_5_reg_758[31:30] <= 2'b00;
    o_d_cast_reg_791[31] <= 1'b0;
    o_x_cast_reg_858[31] <= 1'b0;
end

endmodule //conv_layer
