// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmaxpool_layer.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMaxpool_layer_CfgInitialize(XMaxpool_layer *InstancePtr, XMaxpool_layer_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMaxpool_layer_Start(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMaxpool_layer_IsDone(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMaxpool_layer_IsIdle(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMaxpool_layer_IsReady(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMaxpool_layer_EnableAutoRestart(XMaxpool_layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XMaxpool_layer_DisableAutoRestart(XMaxpool_layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XMaxpool_layer_Set_input_offset(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_INPUT_OFFSET_DATA, Data);
}

u32 XMaxpool_layer_Get_input_offset(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_INPUT_OFFSET_DATA);
    return Data;
}

void XMaxpool_layer_Set_output_offset(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_OUTPUT_OFFSET_DATA, Data);
}

u32 XMaxpool_layer_Get_output_offset(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_OUTPUT_OFFSET_DATA);
    return Data;
}

void XMaxpool_layer_Set_b(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_B_DATA, Data);
}

u32 XMaxpool_layer_Get_b(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_B_DATA);
    return Data;
}

void XMaxpool_layer_Set_od(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_OD_DATA, Data);
}

u32 XMaxpool_layer_Get_od(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_OD_DATA);
    return Data;
}

void XMaxpool_layer_Set_ox(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_OX_DATA, Data);
}

u32 XMaxpool_layer_Get_ox(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_OX_DATA);
    return Data;
}

void XMaxpool_layer_Set_oy(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_OY_DATA, Data);
}

u32 XMaxpool_layer_Get_oy(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_OY_DATA);
    return Data;
}

void XMaxpool_layer_Set_id(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_ID_DATA, Data);
}

u32 XMaxpool_layer_Get_id(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_ID_DATA);
    return Data;
}

void XMaxpool_layer_Set_ix(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IX_DATA, Data);
}

u32 XMaxpool_layer_Get_ix(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IX_DATA);
    return Data;
}

void XMaxpool_layer_Set_iy(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IY_DATA, Data);
}

u32 XMaxpool_layer_Get_iy(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IY_DATA);
    return Data;
}

void XMaxpool_layer_Set_s(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_S_DATA, Data);
}

u32 XMaxpool_layer_Get_s(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_S_DATA);
    return Data;
}

void XMaxpool_layer_Set_k(XMaxpool_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_K_DATA, Data);
}

u32 XMaxpool_layer_Get_k(XMaxpool_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_K_DATA);
    return Data;
}

void XMaxpool_layer_InterruptGlobalEnable(XMaxpool_layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_GIE, 1);
}

void XMaxpool_layer_InterruptGlobalDisable(XMaxpool_layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_GIE, 0);
}

void XMaxpool_layer_InterruptEnable(XMaxpool_layer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IER);
    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XMaxpool_layer_InterruptDisable(XMaxpool_layer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IER);
    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XMaxpool_layer_InterruptClear(XMaxpool_layer *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMaxpool_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XMaxpool_layer_InterruptGetEnabled(XMaxpool_layer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_IER);
}

u32 XMaxpool_layer_InterruptGetStatus(XMaxpool_layer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMaxpool_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMAXPOOL_LAYER_CTRL_BUS_ADDR_ISR);
}

