// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfc_layer.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFc_layer_CfgInitialize(XFc_layer *InstancePtr, XFc_layer_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFc_layer_Start(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFc_layer_IsDone(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFc_layer_IsIdle(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFc_layer_IsReady(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFc_layer_EnableAutoRestart(XFc_layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XFc_layer_DisableAutoRestart(XFc_layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XFc_layer_Set_input_offset(XFc_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_INPUT_OFFSET_DATA, Data);
}

u32 XFc_layer_Get_input_offset(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_INPUT_OFFSET_DATA);
    return Data;
}

void XFc_layer_Set_output_offset(XFc_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_OUTPUT_OFFSET_DATA, Data);
}

u32 XFc_layer_Get_output_offset(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_OUTPUT_OFFSET_DATA);
    return Data;
}

void XFc_layer_Set_batch_size(XFc_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_BATCH_SIZE_DATA, Data);
}

u32 XFc_layer_Get_batch_size(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_BATCH_SIZE_DATA);
    return Data;
}

void XFc_layer_Set_num_inputs(XFc_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_NUM_INPUTS_DATA, Data);
}

u32 XFc_layer_Get_num_inputs(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_NUM_INPUTS_DATA);
    return Data;
}

void XFc_layer_Set_num_outputs(XFc_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_NUM_OUTPUTS_DATA, Data);
}

u32 XFc_layer_Get_num_outputs(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_NUM_OUTPUTS_DATA);
    return Data;
}

void XFc_layer_Set_enable_relu(XFc_layer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_ENABLE_RELU_DATA, Data);
}

u32 XFc_layer_Get_enable_relu(XFc_layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_ENABLE_RELU_DATA);
    return Data;
}

void XFc_layer_InterruptGlobalEnable(XFc_layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_GIE, 1);
}

void XFc_layer_InterruptGlobalDisable(XFc_layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_GIE, 0);
}

void XFc_layer_InterruptEnable(XFc_layer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_IER);
    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XFc_layer_InterruptDisable(XFc_layer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_IER);
    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XFc_layer_InterruptClear(XFc_layer *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFc_layer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XFc_layer_InterruptGetEnabled(XFc_layer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_IER);
}

u32 XFc_layer_InterruptGetStatus(XFc_layer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFc_layer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFC_LAYER_CTRL_BUS_ADDR_ISR);
}

