// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfc_layer.h"

extern XFc_layer_Config XFc_layer_ConfigTable[];

XFc_layer_Config *XFc_layer_LookupConfig(u16 DeviceId) {
	XFc_layer_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFC_LAYER_NUM_INSTANCES; Index++) {
		if (XFc_layer_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFc_layer_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFc_layer_Initialize(XFc_layer *InstancePtr, u16 DeviceId) {
	XFc_layer_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFc_layer_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFc_layer_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

